name: sphinx-linkcheck

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  sphinx-linkcheck:
    name: linkcheck
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8']

    steps:
      - uses: actions/checkout@v2

      - uses: goanpeca/setup-miniconda@v1
        with:
           auto-update-conda: true
           auto-activate-base: false
           environment-file: environment.yaml
           python-version: ${{ matrix.python-version }}
           activate-environment: moad-docs

      - name: linkcheck
        shell: bash -l {0}
        run: |
          make linkcheck

      - uses: pioug/le-slack-message@v1.0.0
        with:
          ACTION_NAME: ${{ github.repository }} Sphinx linkcheck
          JOB: ${{ toJson(job) }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_SALISHSEACAST_WEBHOOK_URL }}
        if: always()

      - uses: pioug/le-slack-message@v1.0.0
        with:
          ACTION_NAME: ${{ github.repository }} Sphinx linkcheck
          JOB: ${{ toJson(job) }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_MIDOSS_WEBHOOK_URL }}
        if: always()
